app_name: "canvas"

server:
  name: "Prod Server"
  debug: False

database:
  driver: "asyncpg"
  type: "postgresql"
  host: "localhost"
  port: 5434
  db_name: "canvas"
  username: "postgres"
  password: "postgres"
  schema_package: "core.repositories.schemas"

ui:
  vite_api_url: "http://localhost:8000"

msg_broker:
  redis:
    host: "localhost"
    port: 6379
    db: 0
    password: "redis"

  rabbitmq:
    host: "localhost"
    port: 5672
    ui_port: 15672
    username: "guest"
    password: "guest"

flow_engine:
  msg_broker: "redis" # redis or "rabbitmq"
  channel: "canvas_flow_engine"

flow_nodes:
  msg_broker: "redis" # redis or "rabbitmq"
  channel: "canvas_flow_node